global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 2m

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: "7518225317:AAGburFciFSDRLttpyiXngNyJX4WNaYLW_w"
        api_url: https://api.telegram.org
        chat_id: 5416946881
        message: '{{ template "telegram.yucca.message" . }}'

templates:
  - "/etc/alertmanager/templates/telegram.tmpl"
